import Head from "next/head";
import About from "../components/About";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Products from "../components/Products";
import Layout from "../components/Layout";
import InitialTransition from "../components/InititalTransition";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section
        id="hero"
        className="brelative bg-[#191919] bg-no-repeat min-h-screen snap-start"
      >
        <Hero />
      </section>

      <section id="products" className="min-h-screen snap-start">
        <Products />
      </section>

      <section id="about" className="min-h-screen snap-start">
        <About />
      </section>

      <section id="footer" className="bg-[#191919] snap-start">
        <Footer />
      </section>
    </Layout>
  );
}
